### ISSUE TITLE
How to reload the cells like reload tableView/CollectionView ?

### ISSUE THREAD

**Issue by hyd00** [manuelescrig/MEVHorizontalContacts#2]

**Comment by PVKonovalov** [comment]
If you want to get quick result  you can add follow lines to MEVHorizontalContacts.m file:
`- (void)reloadData
{
  [_horizontalContactListView reloadData];
}`

and 
`- (void)reloadData;`

to .h

**Comment by hyd00** [comment]
Thanks!
