### ISSUE TITLE
Clear Background Color not working properly.

### ISSUE THREAD

**Issue by hyd00** [manuelescrig/MEVHorizontalContacts#4]
When doing `_horizontalContacts.backgroundColor = [UIColor clearColor];` , the background becomes black instead with a horizontal contacts copy visible in the background as well.

How to fix this @manuelescrig ?

**Comment by manuelescrig** [comment]
Update your library to the new version and it should be working fine.

**Comment by hyd00** [comment]
Fixed. Thank youuuuuu!!!
